FROM ubuntu

ENV JAVA_HOME       /usr/lib/jvm/java-8-oracle

RUN apt-get update && \
  apt-get install -y openjdk-8-jre && \
  apt-get install -y mysql-client

COPY ./target/*.jar /opt/server.jar

CMD [java -jar /opt/server.jar]